// Code auto generated by "generator dbstruct"; DO NOT EDIT.
package dbstruct

type DynamicInnerInnerStruct struct {
	Field4 int `db:"field4,omitempty"`
}
type DynamicInnerStruct struct {
	Field3 int `db:"field3,omitempty"`
	I      main.InnerInnerStruct
}
type DynamicSourceStruct struct {
	Field1 int    `db:"field1,omitempty"`
	Field2 string `db:"field2,omitempty"`
	Child  main.InnerStruct
}
